### ISSUE TITLE
Someone having trouble completing ICE process

### ISSUE THREAD

**Issue by creslin287** [respoke/chan_respoke#7]
Steve Davies has found an ICE topology that seems to be challenging to construct a media path through.  I looked through his traces, and was not able to spend enough time on it to come to a conclusion of some sort.

He has an asterisk full log that seems to have all the info in it.  I apologize if this is a simple error that I missed - I'm still beefing up on my ICE debugging ability.

I'm checking with him to see what info he'll let me attach here.

**Comment by creslin287** [comment]
I talked with him and I can get the Asterisk full log with debug of the ICE process directly to whomever works on this.

**Comment by elbow** [comment]
Hi,

It's me with the problem - happy to provide traces and etc if it will help.

The essence of the issue seems to be that there are two paths between the client and chan_respoke - one is natted in the common way, the other is via a vpn without nat.  The stun server sees only the natted path.  

In our network where we want to use chan_respoke this is a very common topology.

thanks,
Steve

**Comment by chadxz** [comment]
afaik, @elbow is no longer having these issues, so I'm closing this. Feel free to re-open if you want to discuss further
